### ISSUE TITLE
gen-vm: Enable non-sudo dmesg for the given user

### ISSUE THREAD

**Issue by sbates130272** [sbates130272/qemu-minimal#54]
Add a step to cloud-init to ensure the user who is created is given passwordless dmesg access.

**Comment by sbates130272** [comment]
This ansible template shows us one possible solution:
```
- name: Ensure users can access dmesg without sudo # noqa: args[module]
  ansible.builtin.blockinfile:
    path: /etc/sysctl.d/10-kernel-hardening.conf
    state: present
    create: false
    marker_begin: BEGIN (user-setup)
    marker_end: END (user-setup)
    block: |
      kernel.dmesg_restrict = 0
```
